### ISSUE TITLE
[META] issues found with 0.3.0 pre-release test

### ISSUE THREAD

**Issue by J-ZhengLi** [J-ZhengLi/rim#156]
## Issues to fix before releasing 0.3.0
- [x] 1. **CLI** component selection (#136) still not fixed, and the default selections are not shown

## Issues to fix before releasing ~~0.3.1~~ 0.4.0 (because there are some api level changes, the next update won't be a patch update anymore)

- [x] 1. **GUI/CLI** detailed log does not appears when running rustup when installing toolchain (#159)
- [x] 2. **GUI** available toolkit list does not filtering out the one that are already installed (#158) 
- [x] 3. **GUI** when selecting a toolkit to update, the component list shows toolchain components with version `stable v1.82.0` causing it be detected always as the newest version (#158)
- [x] 4. **GUI** when the user click `uninstall` after clicking `update`, the progress starts at 100, and the detailed log carried over from last `update` step, also no detail log of the current `uninstall` steps are shown. (#175 )
- [x] 5. **CLI** when updating toolkit, there's no version record for installed tools, causing them not being selected as update candidates (#167)
- [x] 6. **CLI** when trying to update the toolkit but no update availablle, the manager tool should tells the user that the version of current toolkit is already the latest (#160)
- [x] ~~7. **GUI/CLI** when downloading rustup-init, the download function does not take system proxy into account, causing a `failed to download rustup` error~~ It was not proxy issue, it was because it got blocked by restricted network
- [x] 8. **CLI** manager on windows has no pause and still requires to be open with cmd or powershell (#139)(#170)
