### ISSUE TITLE
[META] missing features (or detected bugs) concluded from 0.4.0 pre-release tests

### ISSUE THREAD

**Issue by J-ZhengLi** [J-ZhengLi/rim#189]
~- [ ] [CLI] `manager update/uninstall/other-subcommands` should still be interactive, unless `-y` option is presented~
- [x] [CLI] missing `--component` option that allows user specify what to install/update (#200)
- [x] [CLI] `-qy` option doesn't silence download progress bar (#193 )
- [x] [CLI] `manager --no-modify-path uninstall` still modifies PATH, and worse, it deletes rustup env variables as well (#194)
- [x] [CLI] `mingw64` still got selected when doing custom interactive installation, even though it was already installed (#195)
- [x] [CLI] `-v` option is too noisy when downloading files, console output is flooded with all `trace` messages (#199)
- [x] [CLI] add a progress spinner when uninstalling via rustup, 'cuz that part took too long on windows (possibly because of windows defender), and user my think the program is stuck
- [x] [CLI] when updating toolkit, the components that are not installed yet should not be pre-selected (#200)
- [ ] #231
- [ ] #230
- [x] [GUI] panic errors are not presented in GUI mode (added thread pool in #204)
- [x] [GUI] bring back `uninstall this manager tool` option when uninstalling
- [x] [GUI][Bug] folder selection can be clicked multiple times to open multiple instance of file picker dialog
- [x] [GUI] after self update, the program does not reopen if it has been started using CMD/PS. And the original executable got renamed to a temp file, we should show a message letting user manually reopen instead of auto restart in this case
- [x] [GUI/CLI] third-party tools in toolset-manifest need display name and an actual name (#197)
